language: java
jdk: openjdk11

script:
- ./spoon-ci-external.sh

env:
  global:
    # sets env variable $GITHUB_TOKEN (from user spoon-bot)
    secure: ZhJ3Z6YeSiFqTyKPKvBRjabPzKR+wWNvSnll2BTQQO2KxSjfJs4Iaj6rSnBtQG5rcS9E1fIhmOShIa3eEayl0WD/FaZSVC2bCrzkJ0rQNNEA+ppCTtuBzMv7NArd+luJ/jBeFd/RSaxLuJz/KPU8CvGvEsbtzhHZ735dU2GDQfYRwIfWLz5ke8N7iYZjdfa6emgO5YJwFgEZRTDr8agluDq1TMn2etMSmxZ4Sa4uPyHbBCGJtEYTuXIt2E/szM39Sn0TzHtR1IULgIQBF6tKsIGFLuMRJu3UtCXmxDCCeURi7TVsUr12S88Td+vrMscyqWIz56Fn//My/NK3hkKALwtjDg3Rv9gzrpPrSvcNef5Fe4oLvGO4NfPaBGrBL9bRUIjT2B6yjS9Wl3RDHgFkDQuLX3zMyvjkvrGCtafI+pclBU02bNxWByA2B80xcEG2VHwTxnwefrLv1UwQOUx5iErQaYnYPnEcihM4O31XY+xMknPZ1jEr3SGkX1XG0Q1JxdKbtFF1aQOOHTODAhnZStt4x3i4i6TJW1KWj9vA3RdbSQ2ifCgm30MjkIE3a7esizolVIXm8DJ0O8M0m4oV/PvHRjRpgO7dxhEuFctEPsA9AzCJFOSpzyhXPkYnJVXhrYJGqGgKCjiP5W/LhZYwAcnYC0q+e0QbkXMMVYJRDzs=
